### PR TITLE
Update View Singletrack with Geoserver WMS

### PR DESCRIPTION
**Pull request by OpenDEM**

### CODE REVIEW

**Comment by wschildbach** [comment]
this changes code in src/js/oseam-views-singltrack.js. It turns out that this code is not actually built (it is not included in wscript). There is almost identical code in singletrack.html.

@OpenDEM @stevo01 I am now wondering which of these two implementations of SingleTrackController should be used and maintained. Do you know?

**Comment by wschildbach** [comment]
I ported these changes to singletrack.html but they don't seem to work. When I include the CQL_Filter, then singletrack.html tries to fetch tiles from the geoserver with URLs of this form:

```
https://depth.openseamap.org/geoserver/openseamap/wms?LAYERS=openseamap%3Atrackpoints_single_track_10&NUMZOOMLEVELS=20&PROJECTION=EPSG%3A900913&TYPE=png&TRANSPARENT=TRUE&CQL_FILTER=track_id%3D%221%22&SERVICE=WMS&VERSION=1.1.1&REQUEST=GetMap&STYLES=&FORMAT=image%2Fpng&SRS=EPSG%3A900913&BBOX=-20037508.34,-10203463.614177,0,9834044.725823&WIDTH=1024&HEIGHT=1024
```

... which fails. The geoserver returns

```
<?xml version="1.0" encoding="UTF-8" standalone="no"?><!DOCTYPE ServiceExceptionReport SYSTEM "http://depth.openseamap.org/geoserver/schemas/wms/1.1.1/WMS_exception_1_1_1.dtd"> <ServiceExceptionReport version="1.1.1" >   <ServiceException code="internalError">
      Rendering process failed. Layers: trackpoints_raw_render_8, trackpoints_raw_render_7, trackpoints_raw_render_6, trackpoints_raw_render_5, trackpoints_raw_render_4, trackpoints_raw_render_3, trackpoints_raw_render_20, trackpoints_raw_render_9, trackpoints_raw_render_2, trackpoints_raw_render_19, trackpoints_raw_render_18, trackpoints_raw_render_17, trackpoints_raw_render_16, trackpoints_raw_render_15, trackpoints_raw_render_14, trackpoints_raw_render_13, trackpoints_raw_render_11, trackpoints_raw_render_10, trackpoints_raw_render_1, trackpoints_raw_render_12
java.io.IOExceptionjava.lang.Double cannot be cast to org.opengis.feature.type.AttributeDescriptor
</ServiceException></ServiceExceptionReport>
```

So I am wondering whether maybe the format for the id is wrong?

**Comment by wschildbach** [comment]
This may be related to https://gis.stackexchange.com/questions/222768/using-filter-functions-in-cql-filter-throws-cannot-be-cast-to-org-opengis-f#:~:text=java.lang.ClassCastException:%20org.geotools.filter.function.FilterFunction_strMatches%20cannot%20be%20cast

**Comment by OpenDEM** [comment]
Yes, since this is an integer value, we have to get rid of the quotes.

**Comment by OpenDEM** [comment]
I created a pull request.

**Pull request merged**
